minimal_mistakes_skin:  contrast #contrast #dark
locale: en-US
title: Blogs by Kush
title_separator: '-'
subtitle: Blogs on ML and Life's philosphy
name: Kush Bhatnagar
description: An amazing website.
#url: 'https://localhost:4000'
url: https://kushbhatnagar.github.io
#baseurl: null
baseurl: "/"
repository: null
teaser: /assets/images/unsplash-image-3.jpg
logo: /assets/images/logo-kb-2.png
masthead_title: null
words_per_minute: 200
comments:
  provider: "disqus"
  disqus:
    shortname: "blogsbykush"
  discourse:
    server: null
  facebook:
    appid: null
    num_posts: null
    colorscheme: null
  utterances:
    theme: null
    issue_term: null
  giscus:
    repo_id: null
    category_name: null
    category_id: null
    discussion_term: null
    reactions_enabled: null
    theme: null
  staticman:
    branch: null
    endpoint: null
reCaptcha:
  siteKey: null
  secret: null
atom_feed:
  path: null
  hide: null
search: true
search_full_content: null
search_provider: null
lunr:
  search_within_pages: true
algolia:
  application_id: null
  index_name: null
  search_only_api_key: null
  powered_by: null
google:
  search_engine_id: null
  instant_search: null
google_site_verification: null
bing_site_verification: null
naver_site_verification: null
yandex_site_verification: null
baidu_site_verification: null
twitter:
  username: null
facebook:
  username: null
  app_id: null
  publisher: null
og_image: null
social:
  type: null
  name: null
  links: null
analytics:
  provider: false
  google:
    tracking_id: null
    anonymize_ip: null
author:
  name: Kush Bhatnagar
  avatar: /assets/images/bio-photo.jpg
  bio: My sole objective is to reduce **complexities** by writing on simple things.
  location: Bangalore
  email: null
  links:
    - label: Email
      icon: fas fa-fw fa-envelope-square
      url: kushbhatnagar86@gmail.com
    - label: Website
      icon: fas fa-fw fa-link
    - label: Twitter
      icon: fab fa-fw fa-twitter-square
      url: 'https://twitter.com/bhatnagarkush'
    - label: GitHub
      icon: fab fa-fw fa-github
      url: 'https://github.com/KushBhatnagar'
    - label: Linkedin
      icon: fab fa-linkedin-in
      url: 'https://www.linkedin.com/in/kushbhatnagar/'
footer:
  links:
    - label: Email
      icon: fas fa-fw fa-envelope-square
      url: kushbhatnagar86@gmail.com
    - label: Website
      icon: fas fa-fw fa-link
    - label: Twitter
      icon: fab fa-fw fa-twitter-square
      url: 'https://twitter.com/bhatnagarkush'
    - label: GitHub
      icon: fab fa-fw fa-github
      url: 'https://github.com/KushBhatnagar'
    - label: Linkedin
      icon: fab fa-linkedin-in
      url: 'https://www.linkedin.com/in/kushbhatnagar/'
include:
  - .htaccess
  - _pages
exclude:
  - '*.sublime-project'
  - '*.sublime-workspace'
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
keep_files:
  - .git
  - .svn
encoding: utf-8
markdown_ext: 'markdown,mkdown,mkdn,mkd,md'
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: |+


incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: 'lsquo,rsquo,ldquo,rdquo'
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed
permalink: '/:categories/:title/'
paginate: 5
paginate_path: '/page:num/'
timezone: null
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
compress_html:
  clippings: all
  ignore:
    envs: development
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: _pages
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ''
      type: docs
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      sidebar:
        nav: docs
  - scope:
      path: ''
      type: recipes
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ''
      type: pets
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  - scope:
      path: ''
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true
